apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-db
  name: javamongodb
  namespace: kafka-cluster
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-db
  name: mongo-deployment
  namespace: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.3
          ports:
            - containerPort: 27017
              hostPort: 27017
          volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          hostPath:
                path: /data/storage/mongodb


#apiVersion: v1
#kind: Service
#metadata:
#  name: javamongodb-service
#  namespace: kafka-cluster
#spec:
#  selector:
#    app: javamongodb
#  ports:
#    - port: 27017
#      targetPort: 27017
#
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: javamongodb-deployment
#  namespace: kafka-cluster
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: javamongodb
#  template:
#    metadata:
#      labels:
#        app: javamongodb
#    spec:
#      hostname: javamongodb
#      containers:
#        - name: javamongodb
#          image: mongo:4.4.3
#          ports:
#            - containerPort: 27017